const enum USER_ROLES {
  STAFF = 'STAFF',
  CLIENT = 'CLIENT',
}

enum REPLY_STATUS {
  JOIN = 'JOIN',
  AWAITING = 'AWAITING',
  CANCELED = 'CANCELED',
  COMPLETED = 'COMPLETED',
  STAFF_NOT_ATTEND = 'STAFF_NOT_ATTEND',
  CLIENT_NOT_ATTEND = 'CLIENT_NOT_ATTEND',
}

enum COMPANY_SERVICE_TYPE {
  WORKOUT = 'WORKOUT',
  MEETING = 'MEETING',
}

const enum STORAGE_KEYS { //TODO move Auth keys to Auth/constants/global.ts
  TOKEN = 'auth-token',
  CODE = 'invite-code',
}

export { USER_ROLES, STORAGE_KEYS, COMPANY_SERVICE_TYPE, REPLY_STATUS };
