const PRIVATE_ROUTES = {
  HOME: 'HOME',
  EVENTS: 'EVENTS',
  EVENT_DETAIL: 'EVENT_DETAIL',
  CREATE_EVENT: 'CREATE_EVENT',
  PROFILE: 'PROFILE',
  PROFILE_HOME: 'PROFILE_HOME',
  ACCOUNT_SETTINGS: 'ACCOUNT_SETTINGS',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CALENDAR: 'CALENDAR',
  NOTIFICATIONS: 'NOTIFICATIONS',
  OVERVIEW: 'OVERVIEW',
  ADD_SERVICE: 'ADD_SERVICE',
} as const;

const ROOT_ROUTES = {
  PRIVATE_STACK: 'PRIVATE_STACK',
  PUBLIC_STACK: 'PUBLIC_STACK',
  TAB_STACK: 'TAB_STACK',
} as const;

const PUBLIC_ROUTES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  INVITE_CODE: 'INVITE_CODE',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
} as const;

const BOTTOM_TAB_ROUTES = {
  HOME: 'HOME_BOTTOM_TAB',
  CALENDAR: 'CALENDAR_BOTTOM_TAB',
  NOTIFICATIONS: 'NOTIFICATIONS_BOTTOM_TAB',
  OVERVIEW: 'OVERVIEW_BOTTOM_TAB',
} as const;

export { PRIVATE_ROUTES, ROOT_ROUTES, PUBLIC_ROUTES, BOTTOM_TAB_ROUTES };
