const PASSWORD_SETTINGS = {
  MIN_LENGTH: 0,
  MAX_LENGTH: 32,
};

const INVITE_CODE_SETTINGS = {
  MIN_LENGTH: 0,
  MAX_LENGTH: 32,
};

const AUTH_STORAGE_KEYS = {
  CORE: 'auth-token-and-company-settings',
};

export { PASSWORD_SETTINGS, AUTH_STORAGE_KEYS, INVITE_CODE_SETTINGS };
